version: "4.16.2"

services:
    imageproxy:
        image: ghcr.io/willnorris/imageproxy
        ports:
            - "8080:8080"
    postgres:
        image: postgres:latest
        container_name: postgres
        environment:
            POSTGRES_USER: paxintrade
            POSTGRES_PASSWORD: uj,kbY12363techaa
            POSTGRES_DB: paxintrade
        ports:
            - "5432:5432"
    pgAdmin:
        image: dpage/pgadmin4
        container_name: pgAdmin
        env_file:
            - ./app.env
        ports:
            - "5050:80"
    redis:
        image: redis:alpine
        container_name: redis_go
        ports:
            - "6379:6379"
        volumes:
            - redisDB:/data
    message-broker:
        image: rabbitmq:3-management-alpine
        container_name: message-broker
        ports:
            - 5672:5672 # for sender and consumer connections
            - 15672:15672 # for serve RabbitMQ GUI
        volumes:
            - ${HOME}/dev-rabbitmq/data/:/var/lib/rabbitmq
            - ${HOME}/dev-rabbitmq/log/:/var/log/rabbitmq
        restart: always
        networks:
            - dev-network
    rethinkdb:
        image: rethinkdb:2.4.2
        ports:
        - 28015:28015
        volumes:
        - ~/apps/rethinkdb/data:/app
volumes:
    redisDB:
    progresDB:
    rethinkdb:
networks:
    # Create a new Docker network.
    dev-network:
        driver: bridge
