version: "4.16.2"

services:
    imageproxy:
        image: ghcr.io/willnorris/imageproxy
        restart: always
        ports:
            - "8080:8080"
    postgres:
        image: postgres:16.1-alpine
        restart: always
        environment:
            POSTGRES_USER: paxintrade
            POSTGRES_PASSWORD: <password>
            POSTGRES_DB: paxintrade
        # ports:
        #     - "5432:5432"
        volumes:
            - ./postgres_data:/var/lib/postgresql/data
    # pgAdmin:
    #     image: dpage/pgadmin4
    #     restart: always
    #     env_file:
    #         - ./app.env
    #     ports:
    #         - "8008:80"
    redis:
        image: redis:alpine
        restart: always
        # ports:
        #     - "16379:6379"
        volumes:
            - ./redis_data:/data
    rabbitmq:
        image: rabbitmq:3-management-alpine
        restart: always
        ports:
            # - 5672:5672 # for sender and consumer connections
            - 15672:15672 # for serve RabbitMQ GUI
        volumes:
            - ./rabbitmq_data:/var/lib/rabbitmq
            - ./rabbitmq_logs:/var/log/rabbitmq
    rethinkdb:
        image: rethinkdb:2.4.2
        restart: always
        # ports:
        #     - 28015:28015
        volumes:
            - ./rethinkdb_data:/app
    paxintrade-api:
        build:
            context: .
            dockerfile: Dockerfile # Dockerfile.dev when development mode, Dockerfile when production mode
        restart: always
        image: paxintrade-api:latest-prod # paxintrade-api:latest-dev when development mode, paxintrade-api:latest-prod when production mode
        ports:
            - "8000:8000/tcp"
        volumes:
            # - .:/app # need when development mode
            - ../img-store:/img-store
        depends_on:
            - redis
            - rethinkdb
            - rabbitmq
            - postgres
